world_size: 4
experiment_name: 'FFHQH_training'
datasets:
    crop_size: 256
    iharmony: "/home/jovyan/datasets/iHarmony4/"
    ffhqh: "/home/jovyan/datasets/ffhqh/"
    dataset_root: "/home/jovyan/datasets/ffhqh/"
    ffhq: "/home/jovyan/datasets/ffhq/images1024x1024/"
task_for_oneformer: "matting"
datasets_to_use_test: ["FFHQH"]
datasets_to_use_val: ["FFHQH"]
dataset_to_use_train: "FFHQH"
batch_size: 16
num_workers: 16
log_dir: "log"
checkpoint_dir: "checkpoints"
load_pretrained: False
checkpoint: "best_ffhqh256.pth"
distributed_addr: "localhost"
lr: 1e-5
epochs: 300
disable_validation: False
disable_mixed_precision: False
log_image_interval: 10
log_image_number: 4
save_model_interval: 5
lambda_losses: 
    default: 0.
    Color: 0.
    PSNR: 2e-1
    FnMSE: 1e-2
    LPIPS: 0.
    Gradient: 1e-2
    L2: 0.
    L1: 0.
    softmax: 1e-4
model:
    grid_counts: [4, 3, 2, 1]
    enc_sizes: [3, 16, 64, 128, 256, 512, 1024]
    init_weights: [0.5, 0.5] # weights of local grided image and global harmonized
    init_value: 0.8
    skips: True
